version: '3.8'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "7777:8080"
